<?php
require_once("input-upload.php");
require_once("input-faille-xss-formateurs.php");
require_once("input-prenom.php");
require_once("input-nom.php");
require_once("input-email.php");
require_once("input-tel.php");
require_once("input-adresse.php");
require_once("input-entrer.php");
require_once("input-contrat.php");
require_once("input-formation.php");
